[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
edition = "2018"
name = "holochain_conductor_client"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
anyhow = "1.0"
holochain_conductor_api = {git = "https://github.com/holochain/holochain", rev = "fa6f19ef2f7586cd0afa6a0103d9a937729eeb9e"}
holochain_types = {git = "https://github.com/holochain/holochain", rev = "fa6f19ef2f7586cd0afa6a0103d9a937729eeb9e"}
holochain_websocket = {git = "https://github.com/holochain/holochain", rev = "fa6f19ef2f7586cd0afa6a0103d9a937729eeb9e"}
serde = "1"
url = "2.2"
