[package]
name = "holochain_client_rust"
version = "0.0.1"
description = "A Rust client for the Holochain Conductor API"
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
edition = "2018"
license = "License: CAL 1.0 https://github.com/holochain/cryptographic-autonomy-license"
homepage = "https://github.com/holochain/holochain-client-rust"
repository = "https://github.com/holochain/holochain-client-rust"
readme = "https://github.com/holochain/holochain-client-rust#readme"
keywords = [ "holochain", "client", "conductor-api" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
anyhow = "1.0"
holochain_conductor_api = "0.0.19"
holochain_types = "0.0.19"
holochain_websocket = "0.0.19"
serde = "1"
url = "2.2"

[dev-dependencies]
holochain = {version = "0.0.119", features = ["test_utils"]}
tokio = {version = "1.3", features = ["full"]}
