[package]
name = "holochain_conductor_client"
version = "0.0.1"
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
anyhow = "1.0"
holochain_conductor_api = "0.0.1"
holochain_websocket = "0.0.1"
holochain_types = "0.0.1"
url = "2.2"
